import express from "express";
import authentication from "./authentication";
import users from "./user";
import blog from "./blog";
import course from "./course";
import courseWeek from "./course-week";
import attachment from "./attachment";
import courseModule from "./course-module";
import quiz from "./quiz";
import quizAnswer from "./quiz-answer";
import module from "./module";
import courseVideo from "./course-video";
import leaderboard from "./leaderboard";
import userProgress from "./user-progress";
import cohort from "./cohort";
import userCohort from "./user-cohort";
import userCourseStatus from "./user-course-status";
import timetable from "./timetable";
import freeCourse from "./free-course";
import overview from "./overview";
import masterclass from "./masterclass";
import admin from "./admin";
import engagement from "./engagement";
import courseAdminTracking from "./courseAdminTracking";
import events from "./events";
import session from "./session";
import facilitator from "./facilitator";
import accountStatus from "./account-status";
import programLeads from "./program-leads";
import changeRequest from "./changeRequest";
import classroom from "./classroom";
import assignment from "./assignment";

const router = express.Router();

export default (): express.Router => {
  authentication(router);
  users(router);
  blog(router);
  course(router);
  courseWeek(router);
  attachment(router);
  courseModule(router);
  quiz(router);
  quizAnswer(router);
  module(router);
  courseVideo(router);
  leaderboard(router);
  userProgress(router);
  userCourseStatus(router);
  cohort(router);
  userCohort(router);
  timetable(router);
  freeCourse(router);
  overview(router);
  masterclass(router);
  admin(router);
  engagement(router);
  courseAdminTracking(router);
  events(router);
  session(router);
  facilitator(router);
  accountStatus(router);
  programLeads(router);
  changeRequest(router);
  classroom(router);
  assignment(router);
  return router;
};
